### ISSUE TITLE
Enable using tool via Docker

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4c#18]
Currently there’s a `Dockerfile` but it’s only useful for running the automated tests. It can’t be used to actually _use_ the tool because when running the tool in a container, the tool can’t access the host system’s clipboard or filesystem.

So we should _either_ find a way to enable usage of the tool via Docker, or make very clear (in the Dockerfile _and_ in the README) that the Dockerfile exists _only_ for running the tests.

**Comment by igoratron** [comment]
So far the only way I was able to successfully run the tool on Docker for Mac is using [XQuartz](https://www.xquartz.org/) by following [these steps](http://sourabhbajaj.com/blog/2017/02/07/gui-applications-docker-mac/). 

It works but the process isn't great :(

**Comment by aviflax** [comment]
Fascinating! I’m not sure it’s worth using Docker for actual usage, given how easy it is to install and use Clojure on MacOS these days (`brew install clojure`). Maybe we should make clear that the Dockerfile is included only to facilitate running the automated tests?

**Comment by igoratron** [comment]
> given how easy it is to install and use Clojure on MacOS these days

Even as a hardcode docker fan, I have to agree. XQuartz is not worth the effort for this.

> Maybe we should make clear that the Dockerfile is included only to facilitate running the automated tests?

Is that Dockerfile needed? Can we use the [official image](https://hub.docker.com/_/clojure/) instead?

**Comment by aviflax** [comment]
> Even as a hardcode docker fan, I have to agree. XQuartz is not worth the effort for this.

OK, cool.

> Is that Dockerfile needed? Can we use the official image instead?

Well, I can definitely simplify the Dockerfile now that the official image has a `tools-deps` variant — which is cool; that variant didn’t exist when I first wanted to use Docker for this project — but I think it would be sub-optimal to get rid of it, because using the Dockerfile enables creating an image [layer] that includes the project’s dependencies, so that we don’t have to re-download those dependencies every time the app code changes. That said, if you are aware of a different approach to doing this — maybe it’s possible to create images via `docker run` commands? — then I’d be happy to consider them. Perhaps we could instead use a shell script like `run_tests.sh` that would get the job done.

**Comment by aviflax** [comment]
Aha, it looks like we can create that local image [layer] [using `docker commit`](https://nathanleclaire.com/blog/2014/09/29/the-dockerfile-is-not-the-source-of-truth-for-your-image/). I’ll give that a try!

**Comment by aviflax** [comment]
Superseded by #21.
